version: "3.9"

services:
  api:
    build: .
    image: solanai:latest
    container_name: solanai-api
    env_file:
      - .env
    environment:
      HOST: 0.0.0.0
      PORT: 5000
      API_PREFIX: /api/v1
      DB_PATH: /app/data/main.db
      CHROMEDRIVER_PATH: /usr/bin/chromedriver
    ports:
      - "5000:5000"
    volumes:
      - data:/app/data
    command: >
      gunicorn -w 2 -b 0.0.0.0:5000 app:create_app()
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:5000/api/v1/ready || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 20s

  worker:
    image: solanai:latest
    container_name: solanai-worker
    env_file:
      - .env
    environment:
      DB_PATH: /app/data/main.db
      CHROMEDRIVER_PATH: /usr/bin/chromedriver
    depends_on:
      api:
        condition: service_healthy
    volumes:
      - data:/app/data
    command: >
      python -m worker.runner

volumes:
  data:
